ovs: Bump submodule to use the recently created branch-3.3.
There was a small change in the mcast_snooping_add_group4() library
function signature.  This was causing scheduled CI runs to fail building
with:

  controller/pinctrl.c:5479:52: error: too few arguments to function call, expected 5, have 4
                                        port_key_data);
                                                     ^
  /Users/runner/work/ovn/ovn/ovs/lib/mcast-snooping.h:203:6: note: 'mcast_snooping_add_group4' declared here
  bool mcast_snooping_add_group4(struct mcast_snooping *ms, ovs_be32 ip4,

Bump the submodule version to the tip of OVS branch-3.3, as this is
the most recent stable branch and fix compilation.

Signed-off-by: Dumitru Ceara <dceara@redhat.com>