ovs: Bump submodule to include latest fixes.
Specifically we care about:
  02be2c318 netdev-linux: Fix inability to apply QoS on ports with custom qdiscs.
  b5d972299 Add support for OpenSSL 3.0 functions.
  1a9482d53 dhparams: Fix .c file generation with OpenSSL >= 3.0.

That's because OVN still configures QoS directly and because on newer
distros compilation fails due to:

  lib/stream-ssl.c: In function 'do_ssl_init':
  lib/stream-ssl.c:1073:5: error: 'SSL_CTX_set_tmp_dh_callback' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
   1073 |     SSL_CTX_set_tmp_dh_callback(ctx, tmp_dh_callback);
        |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Dumitru Ceara <dceara@redhat.com>