pinctrl: Avoid false positive out of bounds warning.
GCC incorrectly reported an out of bounds array access when compiling
with -O2:
  controller/pinctrl.c: In function ‘pinctrl_handle_icmp’:
  controller/pinctrl.c:1673:9: error: ‘memcpy’ offset [0, 19] is out of the bounds [0, 0] [-Werror=array-bounds]
   1673 |         memcpy(data, in_ip, in_ip_len);
        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

GCC version is: 11.2.1 20210728 (Red Hat 11.2.1-1) (GCC)

This happens because the compiler cannot infer that in this specific
case dp_packet_l4(&packet) can never return NULL.

pinctrl_compose_ipv4() calls eth_compose() which calls
dp_packet_set_l3() and always sets 'l4_ofs' to a value that's different
from UINT16_MAX.  Somehow the compiler fails to infer that and
determines that in pinctrl_handle_icmp() the call to dp_packet_l4() can
sometimes return NULL.  That would trigger undefined behavior when
doing:

  struct icmp_header *ih = dp_packet_l4(&packet);
  [...]
  void *data = ih + 1;
  memcpy(data, in_ip, in_ip_len);

The compiler (wrongfully) decides to optimize this for the case when
'ih == NULL' and later reports an out of bounds access warning for:

  memcpy(data, in_ip, in_ip_len);

To avoid this we now explicitly set 'ih->icmp_csum = 0' before writing
data to 'ih + 1'.  That tells the compiler that either writing to
'icmp_csum' will crash (which in our case will never happen) OR after
the write 'ih' is definitely not-NULL.

Reported-by: Ihar Hrachyshka <ihrachys@redhat.com>
Tested-by: Lorenzo Bianconi <lorenzo.bianconi@redhat.com>
Signed-off-by: Dumitru Ceara <dceara@redhat.com>